#!/bin/sh
set -e

cat << 'EOF'

----------------------------------------[COVERAGE CHECKER]----------------------------------
  ___              ___             _____          _     ___  _              _             
 |   \  ___ __ __ / _ \  _ __  ___|_   _|___  ___| |_  / __|| |_   ___  __ | |__ ___  _ _ 
 | |) |/ -_)\ V /| (_) || '_ \(_-<  | | / -_)(_-<|  _|| (__ | ' \ / -_)/ _|| / // -_)| '_|
 |___/ \___| \_/  \___/ | .__//__/  |_| \___|/__/ \__| \___||_||_|\___|\__||_\_\\___||_|  
                        |_|                                                               
RUNNING DEVOPS PRE-COMMIT COVERAGE HOOK

EOF

# Run unit tests with coverage
echo "Running unit tests with coverage..."

# Define a function to handle errors
handle_error() {
  cat << 'EOF'

  ___ _   ___ _   _   _ ___ ___ 
 | __/_\ |_ _| | | | | | _ \ __|
 | _/ _ \ | || |_| |_| |   / _| 
 |_/_/ \_\___|____\___/|_|_\___|

Tests failed or coverage thresholds not met - please resolve these and recommit. Aborting commit.

"------------------------------------[COVERAGE CHECKER -End Of Script]-----------------------"
EOF
  exit 1
}

# Set trap to catch errors and call handle_error
trap 'handle_error' ERR

npm run test:unit:coverage

cat << 'EOF'

  ___ _   _  ___ ___ ___ ___ ___ 
 / __| | | |/ __/ __| __/ __/ __|
 \__ \ |_| | (_| (__| _|\__ \__ \
 |___/\___/ \___\___|___|___/___/

Proceeding with commit...

------------------------------------[COVERAGE CHECKER -End Of Script]-----------------------

EOF